language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "3.0"
before_install:
  - pip install codecov pytest-cov
install:
  - pip install -e .
script:
  - py.test --cov-report xml --cov-config .coveragerc --cov odmpy
after_success:
  - codecov
